# Generated by Django 5.2.3 on 2025-07-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quantity',
        ),
    ]
