# Generated by Django 5.2.3 on 2025-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_category_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='sku',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
